name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test --file pom.xml

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
